### ISSUE TITLE
Allow putting "0-count" cards into a deck

### ISSUE THREAD

**Issue by ScotSalmon** [Alsciende/thronesdb#45]
With the recent addition of several spoiled card packs there are now cards in the database that you can't add to a deck. I'd like to be able to add them to discuss future deck ideas with friends.

An easy way to see the cards I'm referring to is to go to the deck builder, select just the future card packs (Calm Over Westeros and later), enable "show unusable cards", and select all the factions and card types. Around half the cards show max quantity 0. Some of them (the plots, it seems) show "deck limit: undefined" if you hover.

This could be a bug report or feature request, either a bug that the limit is 0 on those cards, or a feature request to add a checkbox like "allow adding cards beyond deck limit" (which would make the deck invalid, like having too many plots) if having the limit as 0 internally is important.

**Comment by Alsciende** [comment]
Thank you for the bug report. It was an error in the database. I fixed it, so you should soon be able to add them to your decks.

**Comment by ScotSalmon** [comment]
Thanks for the quick response. When should I be able to validate it on the live site? (Issue still seems to be happening today.)

**Comment by Alsciende** [comment]
Did you try refreshing the application data, with the link at the bottom of the deckbuilder?

**Comment by ScotSalmon** [comment]
That did it, thanks.
